### PR TITLE
Test for missing publishTime in message

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by mcrumm** [comment]
Hi @kianmeng, thanks for the PR! It is my understanding that messages will always have a non-nil publishTime value. Did you experience different behaviour?

**Comment by kianmeng** [comment]
@mcrumm The missing test case was due to this particular function, https://github.com/dashbitco/broadway_cloud_pub_sub/blob/main/lib/broadway_cloud_pub_sub/pull_client.ex#L130

```elixir
  defp parse_datetime(nil), do: nil
```

**Comment by mcrumm** [comment]
Got it, thanks! :)

**Pull request merged**
